### ISSUE TITLE
Cross-compatability with Terrarian Slimes

### ISSUE THREAD

**Issue by Noaaan** [LapisLiozuli/Slimeology#1]
Hello!
Considering both Terrarian-Slimes and Slimeology add coloured slimes it makes sense to migrate some items and recipes to use something like common tags for coloured slime. This would let you use both variants in recipes, and it helps a lot when making modpacks.
Link to repo: https://github.com/lucaargolo/terrarian-slimes
I will open an issue on both repos (https://github.com/lucaargolo/terrarian-slimes/issues/5), please consider adding this!

**Comment by LapisLiozuli** [comment]
Hi Noaaan,

First of all, thanks for taking a look at Slimeology so soon! 
Moving on, have you tried running the two mods together? I tried it but encountered a mixin conflict as both mods target Piston classes. Please let me know if you've encountered a similar issue.
As for common tags, I plan to add a common tag for Coloured Slime Blocks. The main recipe that uses Coloured Slime Blocks is to craft the Rainbow Slime Block, while I see that the version in Terrarian Slimes are used to craft the Slime Crown. 
However, there are no plans to add a common tag for Coloured Slimeballs in Slimeology. Conversion between different colours is a mechanic that will be expanded upon in future content. 

Hope this addresses your concerns.

**Comment by Noaaan** [comment]
I have yet to run the mod myself. It is in my list of a future modpack I am compiling, and I was considering what slime mod to use (if not both).
If you have some colour conversion planned in the future then it might be alright. It does mean I might have to make some tags with KubeJS, though I was prepared for that.

**Comment by LapisLiozuli** [comment]
I have just added a commit which adds the common tag c:slime_blocks at 288119fa0bab890c25fbe76243fd0fc62c300eaf.
Hopefully within the next two weeks I can rewrite the Piston mixins to enable compatibility with Terrarian Slimes.

**Comment by LapisLiozuli** [comment]
OK, I had unexpected free time today so I finished the compatibility and tested it. You can try it out for yourself as and when it's convenient for you. If nothing else crops up, I'll close the issue.
https://github.com/LapisLiozuli/Slimeology/releases/tag/0.1.2%2B1.16.5
